[build]
  publish = "."
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

# Redirect all URLs to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enable Netlify Forms
[build.processing.html]
  pretty_urls = true